### ISSUE TITLE
Return array instead of string

### ISSUE THREAD

**Issue by kohenkatz** [timacdonald/rule-builder#1]
This package looks really nice, but there's one thing I would change to make it much more efficient.

When you provide a string separated by pipes to the Laravel validator, it [splits the string back into an array](https://github.com/laravel/framework/blob/7839ef638f23a61dd2adb7ce95da9d65e9d42335/src/Illuminate/Validation/Validator.php#L246) immediately.  Therefore, I suggest that you just return the array instead of concatenating the rules back into a string. You already have the array and that's exactly how Laravel is going to use it, so why not?

In most of my projects until this point, I have specified my validation rules as arrays instead of strings in my code.

**Comment by timacdonald** [comment]
Genius! Let's make it happen, on it!

**Comment by timacdonald** [comment]
Hey @kohenkatz, first: thanks for checking out the package and your feedback on it.

I've just done a commit to do this. The default is now that an array is returned, however it is possible to cast to string still.

https://github.com/timacdonald/rule-builder/commit/9c90ced60004e88acb9cbfb428197e1bf088c3ee

Thanks again and let me know any other issues or features you think could improve the package.
