### ISSUE TITLE
Adding custom validation

### ISSUE THREAD

**Issue by karmendra** [timacdonald/rule-builder#3]
Is there any mechanism in this to add custom validation rules. Or are there any plan on doing so.

**Comment by timacdonald** [comment]
Hey @karmendra thanks for the question.

My thinking on this is that Laravel already makes it super simple to add custom validation rules, so I wouldn't want to reimplement that functionality, however I would like you to be able to extend the package so you can easily use your custom validation rules with the package.

I've just tagged v2.2.0 of this package which I've added this functionality to. [You can checkout how to do this here](https://github.com/timacdonald/rule-builder#extending-with-custom-rules).

**Comment by timacdonald** [comment]
Let me know what your thoughts are on this and if this is handy for you. Love to hear any feedback.

**Comment by karmendra** [comment]
Thanks for your response @timacdonald, I didn't use it yet in any of my project, I read about this in laravel-news.com, its really neat and better way to define validation rules, I will use this package in next project for sure, and will also try to adding custom validation and using it in fluent syntax using v2.2.0. Thanks for your efforts in creating this.

Happy Coding,
K

**Comment by timacdonald** [comment]
No worries and thanks for the interest and suggestion!
